<?php

function sum_menu() {
    $items['sum'] = [
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['sum_form'],
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    ];

    $items['sum_success_page'] = [
        'title' => 'Success',
        'page callback' => 'sum_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    ];
    return $items;
}

function sum_form() {
    $form['left_number'] = [
        '#title' => 'Left number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number.'),
        '#element_validate' => ['element_validate_number', 'element_validate_range', 'element_validate_even'],
        '#required' => TRUE,
    ];

    $form['right_number'] = [
        '#title' => 'Right number',
        '#type' => 'textfield',
        '#description' => t('Please enter a number.'),
        '#element_validate' => ['element_validate_number', 'element_validate_range', 'element_validate_even'],
        '#required' => TRUE,
    ];

    $form['submit'] = [
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    ];
    return $form;
}

function sum_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum;

    $form_state['redirect'] = 'sum_success_page';
}

function sum_success() {
    $answer = $_SESSION['sum_output'];
    return 'You calculated a sum! The answer is: ' . $answer;
}

// //custom validation
function element_validate_range($element) {
    if ($element['#value'] >50 || $element['#value'] < -50) {
        form_error($element, t('Number must be less than 50 or greater than -50.'));
    }
}
//custom validation for even numbers
function element_validate_even($element) {
    if ($element['#value'] % 2 !=0) {
        form_error($element, t('Number must be even.'));
    }
}
